using System;
using System.Linq;
using MusicBeeWrapped;

namespace MusicBeeWrapped.Services.UI.Slides
{
    /// <summary>
    /// Finale slide component - Wrap-up slide with year summary and thanks
    /// The final slide that concludes the Wrapped experience
    /// </summary>
    public class FinaleSlide : SlideComponentBase
    {
        public override string SlideId => "finale";
        public override string SlideTitle => "That's a Wrap!";
        public override int SlideOrder => 8;

        public override string GenerateHTML(WrappedStatistics stats, PlayHistory playHistory, int year)
        {
            var topArtist = stats.TopArtists.FirstOrDefault();
            var topTrack = stats.TopTracks.FirstOrDefault();
            var totalMinutes = Math.Round(stats.TotalTracks * 3.5); // Assuming 3.5 min average
            var totalHours = Math.Round(totalMinutes / 60);

            var content = $@"
                <div class='finale-container'>
                    <h2>🎭 That's a Wrap!</h2>
                    <p style='margin-bottom: 2rem; opacity: 0.8;'>Your {year} musical journey in summary</p>
                    
                    <div class='finale-summary'>
                        <div class='finale-stat'>
                            <div class='stat-icon'>🎵</div>
                            <div class='stat-value'>{stats.TotalTracks}</div>
                            <div class='stat-label'>Total Plays</div>
                        </div>
                        <div class='finale-stat'>
                            <div class='stat-icon'>⏰</div>
                            <div class='stat-value'>{totalHours}</div>
                            <div class='stat-label'>Hours Listened</div>
                        </div>
                        <div class='finale-stat'>
                            <div class='stat-icon'>👨‍🎤</div>
                            <div class='stat-value'>{stats.TopArtists.Count()}</div>
                            <div class='stat-label'>Artists Discovered</div>
                        </div>
                    </div>

                    <div class='finale-highlights'>
                        <h3>Your {year} Highlights</h3>
                        <div class='highlight-grid'>
                            <div class='highlight-item'>
                                <span class='highlight-label'>Top Artist:</span>
                                <span class='highlight-value'>{EscapeHtml(topArtist.Key ?? "None")}</span>
                            </div>
                            <div class='highlight-item'>
                                <span class='highlight-label'>Most Played:</span>
                                <span class='highlight-value'>{EscapeHtml(topTrack.Key ?? "None")}</span>
                            </div>
                        </div>
                    </div>

                    <div class='finale-message'>
                        <p>🎶 Thank you for making {year} a musical adventure!</p>
                        <p>Here's to another year of discovering amazing music.</p>
                        <div class='finale-note'>
                            <small>Generated by MusicBee Wrapped • Keep exploring, keep listening!</small>
                        </div>
                    </div>
                </div>";

            return WrapInSlideContainer(content);
        }

        public override string GetInsightText(WrappedStatistics stats, PlayHistory playHistory, int year)
        {
            var totalMinutes = Math.Round(stats.TotalTracks * 3.5);
            var totalHours = Math.Round(totalMinutes / 60);
            
            return $"You spent {totalHours} hours exploring music in {year} - that's a soundtrack worth celebrating!";
        }

        public override bool CanRender(WrappedStatistics stats, PlayHistory playHistory)
        {
            return stats.TotalTracks > 0; // Always show finale if we have any data
        }
    }
}
